# Generated by Django 4.2.6 on 2023-10-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindetails',
            name='UserID',
        ),
        migrations.AlterField(
            model_name='logindetails',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
